stages:
- initial
- scan
- build
- deploy
- test
include:
- project: iiidevops-templates/ci-template
  ref: v2.5.5
  file: ci/template.gitlab-ci.yml
Deploy--InfluxDB:
  stage: deploy
  variables:
    iiidevops: deployed-environments
  script:
  - envsubst < k8s/kustomization.yaml.tmp >  k8s/kustomization.yaml
  - kubectl kustomize k8s/ | kubectl apply -f -
  only:
  - develop
Deploy--Wait InfluxDB:
  stage: deploy
  image:
    name: iiiorg/iiidevops-cli:0.0.7
    entrypoint:
    - ''
  variables:
    iiidevops: deployed-environments
    max_wait: 128
    namespace: ${CI_PROJECT_NAME}
    deploy_name: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-influx
  needs:
  - Deploy--InfluxDB
  script:
  - deploy-wait.pl
  only:
  - develop
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
